name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get to file
        run: |
          curl https://ispip.clang.cn/all_cn_cidr.txt | perl -ne '/^(\d{1,3}(\.\d{1,3}){3}\/\d{1,2})/ && print "IP-CIDR,$1\n"' > all_cn_cidr.list
          sed -i 's/$/&,no-resolve/g' all_cn_cidr.list
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
           files: all_cn_cidr.list












